build:
  nodes:
    analysis:
      environment:
        apt_packages:
          - libmagickwand-dev
          - libmagickcore-dev
        php:
          version: 7.3
          pecl_extensions:
            - apcu
            - imagick
            - zip
