build:
  nodes:
    analysis:
      environment:
        apt_packages:
          - libmagickwand-dev
          - libmagickcore-dev
        php:
          version: "8.0"
          pecl_extensions:
            - apcu
            - imagick
      tests:
        before:
          - composer install --no-interaction --no-scripts
        override:
          - command: phpcs-run
            use_website_config: false