language: php

sudo: false

dist: trusty

env:
  - COMPOSER_OPTS="--ansi --prefer-dist --no-interaction --optimize-autoloader --no-suggest --no-progress"

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 7.3

before_install:
  # disable default memory limit
  - export INI=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo memory_limit = -1 >> $INI
  - echo "extension = apcu.so" >> $INI
  - pear config-set preferred_state beta
  - pecl channel-update pecl.php.net
  - yes | pecl install imagick

install:
  - travis_retry composer install $COMPOSER_OPTS

script:
  - vendor/bin/phplint ./src
  - vendor/bin/phpcs -d memory_limit=-1 --standard=PSR2 --extensions=php ./src
  - vendor/bin/phpspec run
  - vendor/bin/phpunit
