attribute_fields:
    flagbit-table-field: flagbit/table-field
extensions:
    akeneo-attribute-select-filter:
        config:
            entityClass: Flagbit\Bundle\TableAttributeBundle\Entity\AttributeOption
