extensions:
    flagbit-catalog-table-attribute-edit-form:
        module: flagbit/product/field/choices
        parent: pim-attribute-edit-form-form-tabs
        targetZone: container
        position: 110

    flagbit-catalog-table-attribute-edit-form-options-grid:
        module: flagbit/options-grid
        parent: flagbit-catalog-table-attribute-edit-form
        targetZone: form-container
